version: '3.7'
services:
  backend:
    container_name: backend_dev
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
    command: npm run start:dev
    env_file:
        - .env

  sut:
    command: run_tests.sh
